-- ============================================================================
-- MOTTU - DDL LIMPO (SEM INSERTS) PARA PROVISIONAR BD NOVO
-- Schema: RELACAODIRETA (ajuste se necessário)
-- Oracle: 12c+ / XE 21c
-- Inclui:
--  - Sequências
--  - Tabelas
--  - PKs / UNIQUEs / CHECKs
--  - FKs com ON DELETE CASCADE (dependentes de pátio)
--  - NOTIFICAÇÃO com ON DELETE SET NULL
--  - Índice único de Box por pátio (TB_PATIO_ID_PATIO, NOME)
-- Execução:
--   sqlplus relacaoDireta/paulo1@localhost:1521/XEPDB1 @BD/schema_clean.sql
-- ============================================================================

ALTER SESSION SET CURRENT_SCHEMA = RELACAODIRETA;

-- =====================================================
-- SEQUENCES
-- =====================================================
CREATE SEQUENCE SEQ_NOTIFICACAO         MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_BOX              MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_CLIENTE          MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_CNH              MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_CONTATO          MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_ENDERECO         MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_LOG_MOVIMENTACAO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_PATIO            MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_RASTREAMENTO     MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_VEICULO          MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE SEQ_TB_ZONA             MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- =====================================================
-- TABELAS BASE
-- =====================================================
CREATE TABLE TB_CONTATO (
  ID_CONTATO NUMBER,
  EMAIL      VARCHAR2(100),
  TELEFONE1  VARCHAR2(20),
  TELEFONE2  VARCHAR2(20),
  TELEFONE3  VARCHAR2(20),
  CELULAR    VARCHAR2(20),
  OUTRO      VARCHAR2(100),
  OBSERVACAO VARCHAR2(200),
  DDD        NUMBER(10,0),
  DDI        NUMBER(10,0)
);

CREATE TABLE TB_ENDERECO (
  ID_ENDERECO NUMBER,
  CEP         VARCHAR2(9),
  NUMERO      NUMBER(10,0),
  LOGRADOURO  VARCHAR2(50),
  BAIRRO      VARCHAR2(50),
  CIDADE      VARCHAR2(50),
  ESTADO      VARCHAR2(2),
  PAIS        VARCHAR2(50),
  COMPLEMENTO VARCHAR2(60),
  OBSERVACAO  VARCHAR2(200)
);

CREATE TABLE TB_PATIO (
  ID_PATIO                NUMBER,
  NOME_PATIO              VARCHAR2(50)   NOT NULL,
  STATUS                  VARCHAR2(1)    NOT NULL,
  OBSERVACAO              VARCHAR2(500),
  TB_CONTATO_ID_CONTATO   NUMBER         NOT NULL,
  TB_ENDERECO_ID_ENDERECO NUMBER         NOT NULL,
  DATA_CADASTRO           DATE
);

CREATE TABLE TB_BOX (
  ID_BOX           NUMBER,
  NOME             VARCHAR2(50) NOT NULL,
  STATUS           VARCHAR2(1)  NOT NULL,
  DATA_ENTRADA     DATE,
  DATA_SAIDA       DATE,
  OBSERVACAO       VARCHAR2(100),
  TB_PATIO_ID_PATIO NUMBER      NOT NULL
);

CREATE TABLE TB_ZONA (
  ID_ZONA          NUMBER,
  NOME             VARCHAR2(50) NOT NULL,
  STATUS           VARCHAR2(1)  NOT NULL,
  OBSERVACAO       VARCHAR2(100),
  TB_PATIO_ID_PATIO NUMBER      NOT NULL,
  TB_PATIO_STATUS  VARCHAR2(1)  NOT NULL
);

CREATE TABLE TB_VEICULO (
  ID_VEICULO         NUMBER,
  PLACA              VARCHAR2(10) NOT NULL,
  RENAVAM            VARCHAR2(11) NOT NULL,
  CHASSI             VARCHAR2(17) NOT NULL,
  FABRICANTE         VARCHAR2(50) NOT NULL,
  MODELO             VARCHAR2(60) NOT NULL,
  MOTOR              VARCHAR2(30),
  ANO                NUMBER       NOT NULL,
  COMBUSTIVEL        VARCHAR2(20) NOT NULL,
  STATUS             VARCHAR2(20) NOT NULL,
  STATUS_OPERACIONAL VARCHAR2(20),
  TAG_BLE_ID         VARCHAR2(50)
);

CREATE TABLE TB_CLIENTE (
  ID_CLIENTE              NUMBER,
  DATA_CADASTRO           DATE,
  SEXO                    VARCHAR2(2),
  NOME                    VARCHAR2(100),
  SOBRENOME               VARCHAR2(100),
  DATA_NASCIMENTO         DATE,
  CPF                     VARCHAR2(11),
  PROFISSAO               VARCHAR2(50),
  ESTADO_CIVIL            VARCHAR2(50),
  TB_ENDERECO_ID_ENDERECO NUMBER,
  TB_CONTATO_ID_CONTATO   NUMBER
);

CREATE TABLE TB_CNH (
  ID_CNH               NUMBER(19,0),
  ATUALIZADO_EM        TIMESTAMP(6),
  CATEGORIA            VARCHAR2(5),
  CRIADO_EM            TIMESTAMP(6),
  DATA_EMISSAO         DATE,
  DATA_VALIDADE        DATE,
  NUMERO_REGISTRO      VARCHAR2(20),
  TB_CLIENTE_ID_CLIENTE NUMBER(19,0)
);

CREATE TABLE TB_NOTIFICACAO (
  ID_NOTIFICACAO       NUMBER(19,0),
  CATEGORIA            VARCHAR2(255) NOT NULL,
  DADOS_EXTRAS         VARCHAR2(2000),
  DATA_HORA_CRIACAO    TIMESTAMP(6)  NOT NULL,
  DATA_HORA_LEITURA    TIMESTAMP(6),
  LIDA                 NUMBER(1)     NOT NULL,
  MENSAGEM             VARCHAR2(1000) NOT NULL,
  PRIORIDADE           VARCHAR2(255) NOT NULL,
  TIPO                 VARCHAR2(255) NOT NULL,
  TITULO               VARCHAR2(200) NOT NULL,
  URL_REDIRECIONAMENTO VARCHAR2(500),
  TB_PATIO_ID_PATIO    NUMBER,
  TB_BOX_ID_BOX        NUMBER
);

-- Relações auxiliares
CREATE TABLE TB_VEICULOBOX (
  TB_BOX_ID_BOX         NUMBER(19,0),
  TB_VEICULO_ID_VEICULO NUMBER(19,0)
);

CREATE TABLE TB_VEICULOPATIO (
  TB_PATIO_ID_PATIO     NUMBER(19,0),
  TB_PATIO_STATUS       VARCHAR2(255),
  TB_VEICULO_ID_VEICULO NUMBER(19,0)
);

CREATE TABLE TB_VEICULOZONA (
  TB_VEICULO_ID_VEICULO NUMBER(19,0),
  TB_ZONA_ID_ZONA       NUMBER(19,0)
);

CREATE TABLE TB_RASTREAMENTO (
  ID_RASTREAMENTO   NUMBER,
  DATA_RASTREIO     TIMESTAMP(6) WITH LOCAL TIME ZONE,
  METODO_LOCALIZACAO VARCHAR2(20),
  NUM_ANCORAS_USADAS NUMBER(2,0),
  PRECISAO_M         NUMBER(8,3),
  RMSE_M             NUMBER(8,3),
  FONTE_DADOS        VARCHAR2(20),
  LAT_E7             NUMBER(19,0),
  LON_E7             NUMBER(19,0),
  LAT_GRAUS          NUMBER(10,7),
  LON_GRAUS          NUMBER(10,7),
  DATA_HORA_REGISTRO TIMESTAMP(6),
  GPRS_ALTITUDE      NUMBER(7,2),
  GPRS_LATITUDE      NUMBER(11,6),
  GPRS_LONGITUDE     NUMBER(11,6),
  IPS_X              NUMBER(7,3),
  IPS_Y              NUMBER(7,3),
  IPS_Z              NUMBER(7,3)
);

CREATE TABLE TB_RP (
  TB_RASTREAMENTO_ID_RASTREAMENTO NUMBER,
  TB_PATIO_ID_PATIO               NUMBER,
  TB_PATIO_STATUS                 CHAR(1)
);

CREATE TABLE TB_VP (
  TB_VEICULO_ID_VEICULO NUMBER,
  TB_PATIO_ID_PATIO     NUMBER,
  TB_PATIO_STATUS       CHAR(1)
);

CREATE TABLE TB_CONTATOPATIO (
  TB_PATIO_ID_PATIO     NUMBER(19,0),
  TB_PATIO_STATUS       VARCHAR2(255),
  TB_CONTATO_ID_CONTATO NUMBER(19,0)
);

CREATE TABLE TB_ENDERECIOPATIO (
  TB_PATIO_ID_PATIO       NUMBER(19,0),
  TB_PATIO_STATUS         VARCHAR2(255),
  TB_ENDERECO_ID_ENDERECO NUMBER(19,0)
);

CREATE TABLE TB_LOG_MOVIMENTACAO (
  ID_LOG_MOVIMENTACAO          NUMBER(19,0),
  DATA_HORA_MOVIMENTACAO       TIMESTAMP(6),
  OBSERVACOES                  VARCHAR2(500),
  TEMPO_ESTACIONAMENTO_MINUTOS NUMBER(19,0),
  TIPO_MOVIMENTACAO            VARCHAR2(20),
  TB_BOX_ID_BOX                NUMBER(19,0),
  TB_PATIO_ID_PATIO            NUMBER(19,0),
  TB_VEICULO_ID_VEICULO        NUMBER(19,0)
);

CREATE TABLE TB_CLIENTEVEICULO (
  TB_CLIENTE_TB_CONTATO_ID_CONTATO   NUMBER(19,0),
  TB_CLIENTE_TB_ENDERECO_ID_ENDERECO NUMBER(19,0),
  TB_CLIENTE_ID_CLIENTE              NUMBER(19,0),
  TB_VEICULO_ID_VEICULO              NUMBER(19,0)
);

CREATE TABLE TB_CV (
  TB_CLIENTE_ID_CLIENTE              NUMBER,
  TB_CLIENTE_TB_ENDERECO_ID_ENDERECO NUMBER,
  TB_CLIENTE_TB_CONTATO_ID_CONTATO   NUMBER,
  TB_VEICULO_ID_VEICULO              NUMBER
);

-- =====================================================
-- CONSTRAINTS: PK / UNIQUE / CHECK
-- =====================================================
ALTER TABLE TB_PATIO           ADD CONSTRAINT TB_PATIO_PK           PRIMARY KEY (ID_PATIO);
ALTER TABLE TB_BOX             ADD CONSTRAINT TB_BOX_PK             PRIMARY KEY (ID_BOX);
ALTER TABLE TB_ZONA            ADD CONSTRAINT TB_ZONA_PK            PRIMARY KEY (ID_ZONA);
ALTER TABLE TB_VEICULO         ADD CONSTRAINT TB_VEICULO_PK         PRIMARY KEY (ID_VEICULO);
ALTER TABLE TB_CLIENTE         ADD CONSTRAINT TB_CLIENTE_PK         PRIMARY KEY (ID_CLIENTE);
ALTER TABLE TB_ENDERECO        ADD CONSTRAINT TB_ENDERECO_PK        PRIMARY KEY (ID_ENDERECO);
ALTER TABLE TB_CONTATO         ADD CONSTRAINT TB_CONTATO_PK         PRIMARY KEY (ID_CONTATO);
ALTER TABLE TB_RASTREAMENTO    ADD CONSTRAINT TB_RASTREAMENTO_PK    PRIMARY KEY (ID_RASTREAMENTO);
ALTER TABLE TB_NOTIFICACAO     ADD CONSTRAINT TB_NOTIFICACAO_PK     PRIMARY KEY (ID_NOTIFICACAO);
ALTER TABLE TB_LOG_MOVIMENTACAO ADD CONSTRAINT TB_LOG_MOVIMENTACAO_PK PRIMARY KEY (ID_LOG_MOVIMENTACAO);

-- Unicidades
CREATE UNIQUE INDEX UX_BOX_PATIO_NOME ON TB_BOX (TB_PATIO_ID_PATIO, NOME);
ALTER TABLE TB_VEICULO ADD CONSTRAINT UK_VEICULO_TAG UNIQUE (TAG_BLE_ID);

-- CHECKS principais
ALTER TABLE TB_LOG_MOVIMENTACAO ADD CHECK (TIPO_MOVIMENTACAO IN ('ENTRADA','SAIDA'));

-- =====================================================
-- CONSTRAINTS: CHAVES ESTRANGEIRAS (com regras de deleção)
-- =====================================================
-- Pátio -> Contato/Endereço
ALTER TABLE TB_PATIO ADD CONSTRAINT TB_PATIO_TB_CONTATO_FK  FOREIGN KEY (TB_CONTATO_ID_CONTATO)   REFERENCES TB_CONTATO(ID_CONTATO);
ALTER TABLE TB_PATIO ADD CONSTRAINT TB_PATIO_TB_ENDERECO_FK FOREIGN KEY (TB_ENDERECO_ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO);

-- Dependentes diretos de Pátio (CASCADE)
ALTER TABLE TB_BOX            ADD CONSTRAINT FK_BOX_PATIO            FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_ZONA           ADD CONSTRAINT TB_ZONA_TB_PATIO_FK     FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_VEICULOPATIO   ADD CONSTRAINT FK_VEICULOPATIO_PATIO   FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_CONTATOPATIO   ADD CONSTRAINT FK_CONTATOPATIO_PATIO   FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_ENDERECIOPATIO ADD CONSTRAINT FK_ENDERECIOPATIO_PATIO FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_RP             ADD CONSTRAINT FK_RP_PATIO             FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;
ALTER TABLE TB_VP             ADD CONSTRAINT FK_VP_PATIO             FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE CASCADE;

-- Outras FKs
ALTER TABLE TB_CLIENTE  ADD CONSTRAINT TB_CLIENTE_TB_CONTATO_FK  FOREIGN KEY (TB_CONTATO_ID_CONTATO)   REFERENCES TB_CONTATO(ID_CONTATO);
ALTER TABLE TB_CLIENTE  ADD CONSTRAINT TB_CLIENTE_TB_ENDERECO_FK FOREIGN KEY (TB_ENDERECO_ID_ENDERECO) REFERENCES TB_ENDERECO(ID_ENDERECO);

ALTER TABLE TB_CNH      ADD CONSTRAINT FK_CNH_CLIENTE            FOREIGN KEY (TB_CLIENTE_ID_CLIENTE)   REFERENCES TB_CLIENTE(ID_CLIENTE);

ALTER TABLE TB_VEICULOBOX       ADD CONSTRAINT FK_VEICULOBOX_BOX     FOREIGN KEY (TB_BOX_ID_BOX)         REFERENCES TB_BOX(ID_BOX);
ALTER TABLE TB_VEICULOBOX       ADD CONSTRAINT FK_VEICULOBOX_VEICULO FOREIGN KEY (TB_VEICULO_ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO);

ALTER TABLE TB_VEICULOZONA      ADD CONSTRAINT FK_VEICULOZONA_VEICULO FOREIGN KEY (TB_VEICULO_ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO);
ALTER TABLE TB_VEICULOZONA      ADD CONSTRAINT FK_VEICULOZONA_ZONA     FOREIGN KEY (TB_ZONA_ID_ZONA)       REFERENCES TB_ZONA(ID_ZONA);

ALTER TABLE TB_RP               ADD CONSTRAINT TB_RP_TB_RASTREAMENTO_FK FOREIGN KEY (TB_RASTREAMENTO_ID_RASTREAMENTO) REFERENCES TB_RASTREAMENTO(ID_RASTREAMENTO);
ALTER TABLE TB_VP               ADD CONSTRAINT TB_VP_TB_VEICULO_FK       FOREIGN KEY (TB_VEICULO_ID_VEICULO)           REFERENCES TB_VEICULO(ID_VEICULO);

ALTER TABLE TB_LOG_MOVIMENTACAO ADD CONSTRAINT FK_LOG_BOX      FOREIGN KEY (TB_BOX_ID_BOX)      REFERENCES TB_BOX(ID_BOX);
ALTER TABLE TB_LOG_MOVIMENTACAO ADD CONSTRAINT FK_LOG_PATIO    FOREIGN KEY (TB_PATIO_ID_PATIO)  REFERENCES TB_PATIO(ID_PATIO);
ALTER TABLE TB_LOG_MOVIMENTACAO ADD CONSTRAINT FK_LOG_VEICULO  FOREIGN KEY (TB_VEICULO_ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO);

ALTER TABLE TB_CLIENTEVEICULO ADD CONSTRAINT FK_CV_VEICULO  FOREIGN KEY (TB_VEICULO_ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO);
ALTER TABLE TB_CLIENTEVEICULO ADD CONSTRAINT FK_CV_CLIENTE  FOREIGN KEY (TB_CLIENTE_ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE);

ALTER TABLE TB_CV ADD CONSTRAINT FK_CV_TB_CLIENTE  FOREIGN KEY (TB_CLIENTE_ID_CLIENTE)              REFERENCES TB_CLIENTE(ID_CLIENTE);
ALTER TABLE TB_CV ADD CONSTRAINT FK_CV_TB_VEICULO  FOREIGN KEY (TB_VEICULO_ID_VEICULO)              REFERENCES TB_VEICULO(ID_VEICULO);

-- NOTIFICAÇÕES: não bloquear deleções de pátio/box
ALTER TABLE TB_NOTIFICACAO ADD CONSTRAINT FK_NOTIF_PATIO FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO) ON DELETE SET NULL;
ALTER TABLE TB_NOTIFICACAO ADD CONSTRAINT FK_NOTIF_BOX   FOREIGN KEY (TB_BOX_ID_BOX)     REFERENCES TB_BOX(ID_BOX)     ON DELETE SET NULL;

COMMIT;



