-- Script para verificar contatos e endereços órfãos
SELECT 'CONTATOS ÓRFÃOS:' as INFO FROM DUAL;
SELECT COUNT(*) as TOTAL_CONTATOS_ORFAOS
FROM TB_CONTATO c 
WHERE NOT EXISTS (
    SELECT 1 FROM TB_CLIENTE cl 
    WHERE cl.TB_CONTATO_ID_CONTATO = c.ID_CONTATO
);

SELECT 'ENDEREÇOS ÓRFÃOS:' as INFO FROM DUAL;
SELECT COUNT(*) as TOTAL_ENDERECOS_ORFAOS
FROM TB_ENDERECO e 
WHERE NOT EXISTS (
    SELECT 1 FROM TB_CLIENTE cl 
    WHERE cl.TB_ENDERECO_ID_ENDERECO = e.ID_ENDERECO
);

-- Listar contatos órfãos
SELECT 'CONTATOS ÓRFÃOS (detalhes):' as INFO FROM DUAL;
SELECT ID_CONTATO, EMAIL, TELEFONE1, CELULAR
FROM TB_CONTATO c 
WHERE NOT EXISTS (
    SELECT 1 FROM TB_CLIENTE cl 
    WHERE cl.TB_CONTATO_ID_CONTATO = c.ID_CONTATO
);

-- Listar endereços órfãos
SELECT 'ENDEREÇOS ÓRFÃOS (detalhes):' as INFO FROM DUAL;
SELECT ID_ENDERECO, CEP, LOGRADOURO, BAIRRO, CIDADE
FROM TB_ENDERECO e 
WHERE NOT EXISTS (
    SELECT 1 FROM TB_CLIENTE cl 
    WHERE cl.TB_ENDERECO_ID_ENDERECO = e.ID_ENDERECO
);

-- Verificar todos os contatos
SELECT 'TODOS OS CONTATOS:' as INFO FROM DUAL;
SELECT ID_CONTATO, EMAIL, TELEFONE1, CELULAR FROM TB_CONTATO;

-- Verificar todos os clientes
SELECT 'TODOS OS CLIENTES:' as INFO FROM DUAL;
SELECT ID_CLIENTE, NOME, SOBRENOME, TB_CONTATO_ID_CONTATO, TB_ENDERECO_ID_ENDERECO FROM TB_CLIENTE;



