-- ==================================================
-- SCRIPT SQL PARA CRIAÇÃO DA TABELA TB_LOG_MOVIMENTACAO
-- ==================================================
-- Execute este script diretamente no seu Oracle se necessário
-- Normalmente o Hibernate criará automaticamente com DDL auto = update

-- Criação da tabela TB_LOG_MOVIMENTACAO para registro de movimentações
CREATE TABLE TB_LOG_MOVIMENTACAO (
    ID_LOG_MOVIMENTACAO NUMBER(19,0) NOT NULL,
    TB_VEICULO_ID_VEICULO NUMBER(19,0) NOT NULL,
    TB_BOX_ID_BOX NUMBER(19,0) NOT NULL,
    TB_PATIO_ID_PATIO NUMBER(19,0) NOT NULL,
    TIPO_MOVIMENTACAO VARCHAR2(20) NOT NULL CHECK (TIPO_MOVIMENTACAO IN ('ENTRADA', 'SAIDA')),
    DATA_HORA_MOVIMENTACAO TIMESTAMP NOT NULL,
    TEMPO_ESTACIONAMENTO_MINUTOS NUMBER(19,0),
    OBSERVACOES VARCHAR2(500),
    CONSTRAINT PK_TB_LOG_MOVIMENTACAO PRIMARY KEY (ID_LOG_MOVIMENTACAO)
);

-- Criação da sequence para TB_LOG_MOVIMENTACAO
CREATE SEQUENCE SEQ_TB_LOG_MOVIMENTACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOMAXVALUE;

-- Criação dos índices para melhor performance
CREATE INDEX IDX_LOG_MOV_VEICULO ON TB_LOG_MOVIMENTACAO(TB_VEICULO_ID_VEICULO);
CREATE INDEX IDX_LOG_MOV_BOX ON TB_LOG_MOVIMENTACAO(TB_BOX_ID_BOX);
CREATE INDEX IDX_LOG_MOV_PATIO ON TB_LOG_MOVIMENTACAO(TB_PATIO_ID_PATIO);
CREATE INDEX IDX_LOG_MOV_TIPO ON TB_LOG_MOVIMENTACAO(TIPO_MOVIMENTACAO);
CREATE INDEX IDX_LOG_MOV_DATA ON TB_LOG_MOVIMENTACAO(DATA_HORA_MOVIMENTACAO);

-- Adição das foreign keys
ALTER TABLE TB_LOG_MOVIMENTACAO 
ADD CONSTRAINT FK_LOG_MOV_VEICULO 
FOREIGN KEY (TB_VEICULO_ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO);

ALTER TABLE TB_LOG_MOVIMENTACAO 
ADD CONSTRAINT FK_LOG_MOV_BOX 
FOREIGN KEY (TB_BOX_ID_BOX) REFERENCES TB_BOX(ID_BOX);

ALTER TABLE TB_LOG_MOVIMENTACAO 
ADD CONSTRAINT FK_LOG_MOV_PATIO 
FOREIGN KEY (TB_PATIO_ID_PATIO) REFERENCES TB_PATIO(ID_PATIO);

-- Comentários para documentação
COMMENT ON TABLE TB_LOG_MOVIMENTACAO IS 'Tabela para registro de movimentações de veículos (entrada e saída)';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.ID_LOG_MOVIMENTACAO IS 'Identificador único do log de movimentação';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.TB_VEICULO_ID_VEICULO IS 'Referência ao veículo que realizou a movimentação';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.TB_BOX_ID_BOX IS 'Referência ao box utilizado na movimentação';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.TB_PATIO_ID_PATIO IS 'Referência ao pátio onde ocorreu a movimentação';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.TIPO_MOVIMENTACAO IS 'Tipo de movimentação: ENTRADA ou SAIDA';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.DATA_HORA_MOVIMENTACAO IS 'Data e hora da movimentação';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.TEMPO_ESTACIONAMENTO_MINUTOS IS 'Tempo de estacionamento em minutos (preenchido na saída)';
COMMENT ON COLUMN TB_LOG_MOVIMENTACAO.OBSERVACOES IS 'Observações sobre a movimentação';

-- ==================================================
-- VERIFICAÇÃO SE A TABELA FOI CRIADA CORRETAMENTE
-- ==================================================
SELECT 'Tabela TB_LOG_MOVIMENTACAO criada com sucesso!' AS STATUS FROM DUAL;

-- Verificar estrutura da tabela
DESC TB_LOG_MOVIMENTACAO;

-- Verificar constraints
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'TB_LOG_MOVIMENTACAO';

-- Verificar índices
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME 
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME = 'TB_LOG_MOVIMENTACAO';

