-- Script SQL para CORRIGIR MANUALMENTE a inconsistência
-- ATENÇÃO: Execute apenas se o backend não conseguir corrigir automaticamente

-- 1. Primeiro, verificar o estado atual
SELECT 
    'ANTES DA CORREÇÃO' as STATUS,
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    e.ESTA_ESTACIONADO,
    e.DATA_SAIDA
FROM TB_ESTACIONAMENTO e
JOIN TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
WHERE v.PLACA IN ('EGX1D92', 'EGC4F67')
AND e.ESTA_ESTACIONADO = 1
ORDER BY e.ID_ESTACIONAMENTO;

-- 2. CORRIGIR: Atualizar TB_ESTACIONAMENTO para boxes que estão com STATUS='L' mas têm estacionamento ativo
UPDATE TB_ESTACIONAMENTO e
SET 
    e.ESTA_ESTACIONADO = 0,
    e.DATA_SAIDA = CURRENT_TIMESTAMP,
    e.DATA_ULTIMA_ATUALIZACAO = CURRENT_TIMESTAMP
WHERE e.ESTA_ESTACIONADO = 1
AND EXISTS (
    SELECT 1 
    FROM TB_BOX b 
    WHERE b.ID_BOX = e.TB_BOX_ID_BOX 
    AND b.STATUS = 'L'
);

-- 3. Verificar quantas linhas foram atualizadas
SELECT SQL%ROWCOUNT as LINHAS_ATUALIZADAS FROM DUAL;

-- 4. COMMIT da transação
COMMIT;

-- 5. Verificar o estado após a correção
SELECT 
    'APÓS A CORREÇÃO' as STATUS,
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    e.ESTA_ESTACIONADO,
    e.DATA_SAIDA
FROM TB_ESTACIONAMENTO e
JOIN TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
WHERE v.PLACA IN ('EGX1D92', 'EGC4F67')
ORDER BY e.DATA_ULTIMA_ATUALIZACAO DESC;

-- 6. Verificar se ainda há inconsistências
SELECT 
    COUNT(*) as INCONSISTENCIAS_RESTANTES
FROM TB_ESTACIONAMENTO e
JOIN TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
WHERE e.ESTA_ESTACIONADO = 1
AND b.STATUS = 'L';



