-- Script para TESTAR e MONITORAR duplicações de estacionamento
-- Execute este script periodicamente ou após cada operação de estacionamento

-- ==================================================
-- 1. DETECTAR DUPLICAÇÕES ATIVAS (CRÍTICO)
-- ==================================================
SELECT 
    '⚠️ DUPLICAÇÃO DETECTADA!' as ALERTA,
    v.PLACA,
    COUNT(*) as TOTAL_ESTACIONAMENTOS_ATIVOS,
    LISTAGG(
        'ID: ' || e.ID_ESTACIONAMENTO || ' | Box: ' || b.NOME || ' | Pátio: ' || p.NOME_PATIO || ' | Data: ' || 
        TO_CHAR(e.DATA_ENTRADA, 'DD/MM/YYYY HH24:MI:SS'), 
        ' | '
    ) WITHIN GROUP (ORDER BY e.DATA_ENTRADA DESC) as DETALHES_ESTACIONAMENTOS,
    MIN(e.DATA_ENTRADA) as PRIMEIRA_ENTRADA,
    MAX(e.DATA_ENTRADA) as ULTIMA_ENTRADA
FROM RELACAODIRETA.TB_VEICULO v
JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON v.ID_VEICULO = e.TB_VEICULO_ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE e.ESTA_ESTACIONADO = 1
GROUP BY v.PLACA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- ==================================================
-- 2. VERIFICAR SE HÁ BOXES COM STATUS INCONSISTENTE
-- ==================================================
SELECT 
    '⚠️ INCONSISTÊNCIA BOX/ESTACIONAMENTO!' as ALERTA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    e.ID_ESTACIONAMENTO,
    e.ESTA_ESTACIONADO,
    v.PLACA,
    p.NOME_PATIO
FROM RELACAODIRETA.TB_BOX b
INNER JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON b.ID_BOX = e.TB_BOX_ID_BOX AND e.ESTA_ESTACIONADO = 1
LEFT JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
LEFT JOIN RELACAODIRETA.TB_PATIO p ON b.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE b.STATUS = 'L'
ORDER BY b.ID_BOX;

-- ==================================================
-- 3. VERIFICAR TODOS OS ESTACIONAMENTOS ATIVOS
-- ==================================================
SELECT 
    '📊 ESTACIONAMENTOS ATIVOS' as STATUS,
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    p.ID_PATIO,
    p.NOME_PATIO,
    e.ESTA_ESTACIONADO,
    TO_CHAR(e.DATA_ENTRADA, 'DD/MM/YYYY HH24:MI:SS') as DATA_ENTRADA,
    TO_CHAR(e.DATA_ULTIMA_ATUALIZACAO, 'DD/MM/YYYY HH24:MI:SS') as ULTIMA_ATUALIZACAO
FROM RELACAODIRETA.TB_ESTACIONAMENTO e
JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE e.ESTA_ESTACIONADO = 1
ORDER BY v.PLACA, e.DATA_ENTRADA DESC;

-- ==================================================
-- 4. RESUMO: CONTAGEM DE ESTACIONAMENTOS ATIVOS POR PLACA
-- ==================================================
SELECT 
    v.PLACA,
    COUNT(*) as TOTAL_ATIVOS,
    CASE 
        WHEN COUNT(*) > 1 THEN '❌ DUPLICADO!'
        WHEN COUNT(*) = 1 THEN '✅ OK'
        ELSE 'ℹ️ SEM ESTACIONAMENTO'
    END as STATUS
FROM RELACAODIRETA.TB_VEICULO v
JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON v.ID_VEICULO = e.TB_VEICULO_ID_VEICULO
WHERE e.ESTA_ESTACIONADO = 1
GROUP BY v.PLACA
ORDER BY COUNT(*) DESC, v.PLACA;

-- ==================================================
-- 5. VERIFICAR SE HÁ BOXES OCUPADOS SEM ESTACIONAMENTO ATIVO
-- ==================================================
SELECT 
    '⚠️ BOX OCUPADO SEM ESTACIONAMENTO ATIVO!' as ALERTA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    b.DATA_ENTRADA,
    b.DATA_SAIDA
FROM RELACAODIRETA.TB_BOX b
WHERE b.STATUS = 'O'
AND NOT EXISTS (
    SELECT 1 
    FROM RELACAODIRETA.TB_ESTACIONAMENTO e 
    WHERE e.TB_BOX_ID_BOX = b.ID_BOX 
    AND e.ESTA_ESTACIONADO = 1
)
ORDER BY b.ID_BOX;



