-- Script para verificar múltiplos estacionamentos ativos para a mesma placa
-- Execute no SQL Developer

-- 1. Verificar se há múltiplos estacionamentos ativos para a mesma placa
SELECT 
    v.PLACA,
    COUNT(*) as TOTAL_ESTACIONAMENTOS_ATIVOS,
    LISTAGG(e.ID_ESTACIONAMENTO || ' (Box: ' || b.NOME || ', Pátio: ' || p.NOME_PATIO || ')', ', ') 
        WITHIN GROUP (ORDER BY e.ID_ESTACIONAMENTO) as DETALHES_ESTACIONAMENTOS
FROM RELACAODIRETA.TB_VEICULO v
JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON v.ID_VEICULO = e.TB_VEICULO_ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE e.ESTA_ESTACIONADO = 1
GROUP BY v.PLACA
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- 2. Verificar todos os estacionamentos ativos atualmente
SELECT 
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    p.ID_PATIO,
    p.NOME_PATIO,
    e.ESTA_ESTACIONADO,
    e.DATA_ENTRADA,
    e.DATA_SAIDA,
    TO_CHAR(e.DATA_ULTIMA_ATUALIZACAO, 'DD/MM/YYYY HH24:MI:SS') as ULTIMA_ATUALIZACAO
FROM RELACAODIRETA.TB_ESTACIONAMENTO e
JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE e.ESTA_ESTACIONADO = 1
ORDER BY v.PLACA, e.DATA_ENTRADA DESC;

-- 3. Verificar inconsistências: boxes com STATUS='L' mas com estacionamento ativo
SELECT 
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    e.ID_ESTACIONAMENTO,
    e.ESTA_ESTACIONADO,
    v.PLACA,
    p.NOME_PATIO
FROM RELACAODIRETA.TB_BOX b
INNER JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON b.ID_BOX = e.TB_BOX_ID_BOX AND e.ESTA_ESTACIONADO = 1
LEFT JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
LEFT JOIN RELACAODIRETA.TB_PATIO p ON b.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE b.STATUS = 'L'
ORDER BY b.ID_BOX;







