-- Script URGENTE: Verificar qual placa está ocupando curitiba001
-- Execute no SQL Developer

-- 1. VERIFICAR QUAL PLACA ESTÁ NO BOX curitiba001
SELECT 
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    p.ID_PATIO,
    p.NOME_PATIO,
    e.ESTA_ESTACIONADO,
    TO_CHAR(e.DATA_ENTRADA, 'DD/MM/YYYY HH24:MI:SS') as DATA_ENTRADA,
    TO_CHAR(e.DATA_ULTIMA_ATUALIZACAO, 'DD/MM/YYYY HH24:MI:SS') as ULTIMA_ATUALIZACAO
FROM RELACAODIRETA.TB_ESTACIONAMENTO e
JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE b.NOME = 'curitiba001'
AND e.ESTA_ESTACIONADO = 1
ORDER BY e.DATA_ULTIMA_ATUALIZACAO DESC;

-- 2. VERIFICAR TODOS OS ESTACIONAMENTOS ATIVOS DA PLACA EGX1D92
SELECT 
    e.ID_ESTACIONAMENTO,
    v.PLACA,
    b.ID_BOX,
    b.NOME as BOX_NOME,
    b.STATUS as BOX_STATUS,
    p.ID_PATIO,
    p.NOME_PATIO,
    e.ESTA_ESTACIONADO,
    TO_CHAR(e.DATA_ENTRADA, 'DD/MM/YYYY HH24:MI:SS') as DATA_ENTRADA,
    TO_CHAR(e.DATA_ULTIMA_ATUALIZACAO, 'DD/MM/YYYY HH24:MI:SS') as ULTIMA_ATUALIZACAO
FROM RELACAODIRETA.TB_ESTACIONAMENTO e
JOIN RELACAODIRETA.TB_VEICULO v ON e.TB_VEICULO_ID_VEICULO = v.ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE UPPER(v.PLACA) = 'EGX1D92'
AND e.ESTA_ESTACIONADO = 1
ORDER BY e.DATA_ENTRADA DESC;

-- 3. VERIFICAR TODOS OS ESTACIONAMENTOS ATIVOS (PARA VER SE HÁ MÚLTIPLOS PARA A MESMA PLACA)
SELECT 
    v.PLACA,
    COUNT(*) as TOTAL_ATIVOS,
    LISTAGG(
        b.NOME || ' (Pátio: ' || p.NOME_PATIO || ')', 
        ', '
    ) WITHIN GROUP (ORDER BY e.DATA_ENTRADA DESC) as BOXES_OCUPADOS
FROM RELACAODIRETA.TB_VEICULO v
JOIN RELACAODIRETA.TB_ESTACIONAMENTO e ON v.ID_VEICULO = e.TB_VEICULO_ID_VEICULO
JOIN RELACAODIRETA.TB_BOX b ON e.TB_BOX_ID_BOX = b.ID_BOX
JOIN RELACAODIRETA.TB_PATIO p ON e.TB_PATIO_ID_PATIO = p.ID_PATIO
WHERE e.ESTA_ESTACIONADO = 1
GROUP BY v.PLACA
ORDER BY COUNT(*) DESC, v.PLACA;







