-- ============================================================================
-- MOTTU - Migração para Tabela de CNH
-- Compatível com Oracle 12c+ (IDENTITY)
-- ============================================================================
-- Este script cria a tabela TB_CNH para armazenar dados da Carteira Nacional de Habilitação
-- ============================================================================

-- 1) TABELA TB_CNH
CREATE TABLE TB_CNH (
  id_cnh           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_emissao     DATE NOT NULL,
  data_validade    DATE NOT NULL,
  numero_registro  VARCHAR2(20) NOT NULL UNIQUE,
  categoria        VARCHAR2(5) NOT NULL,
  tb_cliente_id_cliente NUMBER NOT NULL,
  criado_em        TIMESTAMP DEFAULT SYSTIMESTAMP,
  atualizado_em    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 2) COMENTÁRIOS DA TABELA E COLUNAS
COMMENT ON TABLE TB_CNH IS 'Carteira Nacional de Habilitação dos clientes';
COMMENT ON COLUMN TB_CNH.id_cnh IS 'Identificador único da CNH';
COMMENT ON COLUMN TB_CNH.data_emissao IS 'Data de emissão da CNH';
COMMENT ON COLUMN TB_CNH.data_validade IS 'Data de validade da CNH';
COMMENT ON COLUMN TB_CNH.numero_registro IS 'Número de registro da CNH (único)';
COMMENT ON COLUMN TB_CNH.categoria IS 'Categoria da CNH (A, B, C, D, E, AB, AC, AD, AE)';
COMMENT ON COLUMN TB_CNH.tb_cliente_id_cliente IS 'Referência ao cliente proprietário da CNH';

-- 3) CONSTRAINTS DE VALIDAÇÃO
-- Constraint para validar categoria da CNH
ALTER TABLE TB_CNH ADD CONSTRAINT ck_cnh_categoria 
CHECK (categoria IN ('A', 'B', 'C', 'D', 'E', 'AB', 'AC', 'AD', 'AE'));

-- Constraint para validar que data_validade > data_emissao
ALTER TABLE TB_CNH ADD CONSTRAINT ck_cnh_datas 
CHECK (data_validade > data_emissao);

-- Constraint para validar que data_emissao não pode ser muito antiga (máximo 10 anos)
ALTER TABLE TB_CNH ADD CONSTRAINT ck_cnh_emissao_valida 
CHECK (data_emissao >= ADD_MONTHS(SYSDATE, -120));

-- Constraint para validar formato do número de registro (11 dígitos)
ALTER TABLE TB_CNH ADD CONSTRAINT ck_cnh_numero_registro 
CHECK (REGEXP_LIKE(numero_registro, '^[0-9]{11}$'));

-- 4) FOREIGN KEY para TB_CLIENTE
ALTER TABLE TB_CNH ADD CONSTRAINT fk_cnh_cliente 
FOREIGN KEY (tb_cliente_id_cliente) REFERENCES TB_CLIENTE(id_cliente);

-- 5) ÍNDICES para performance
CREATE INDEX ix_cnh_cliente ON TB_CNH (tb_cliente_id_cliente);
CREATE INDEX ix_cnh_numero_registro ON TB_CNH (numero_registro);
CREATE INDEX ix_cnh_data_validade ON TB_CNH (data_validade);
CREATE INDEX ix_cnh_categoria ON TB_CNH (categoria);

-- 6) SEQUENCE para TB_CNH (se necessário para compatibilidade)
CREATE SEQUENCE SEQ_TB_CNH
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 7) TRIGGER para atualizar campo atualizado_em
CREATE OR REPLACE TRIGGER tr_cnh_atualizado_em
BEFORE UPDATE ON TB_CNH
FOR EACH ROW
BEGIN
    :NEW.atualizado_em := SYSTIMESTAMP;
END;
/

-- 8) TRIGGER para validar idade mínima do motorista (18 anos)
CREATE OR REPLACE TRIGGER tr_cnh_validar_idade_motorista
BEFORE INSERT OR UPDATE ON TB_CNH
FOR EACH ROW
DECLARE
    v_data_nascimento DATE;
    v_idade_anos NUMBER;
BEGIN
    -- Buscar data de nascimento do cliente
    SELECT c.data_nascimento INTO v_data_nascimento
    FROM TB_CLIENTE c
    WHERE c.id_cliente = :NEW.tb_cliente_id_cliente;
    
    -- Calcular idade em anos
    v_idade_anos := FLOOR(MONTHS_BETWEEN(:NEW.data_emissao, v_data_nascimento) / 12);
    
    -- Validar se tem pelo menos 18 anos na data de emissão
    IF v_idade_anos < 18 THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'Cliente deve ter pelo menos 18 anos na data de emissão da CNH. Idade atual: ' || v_idade_anos || ' anos');
    END IF;
END;
/

COMMIT;




