-- =====================================================
-- Script SIMPLES para corrigir TB_NOTIFICACAO na VPS
-- Execute linha por linha se necessário
-- =====================================================

-- Adicionar colunas faltantes
ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO ADD TB_VEICULO_ID_VEICULO NUMBER(19);
ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO ADD TB_PATIO_ID_PATIO NUMBER(19);
ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO ADD TB_BOX_ID_BOX NUMBER(19);

-- Criar Foreign Keys
ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO 
  ADD CONSTRAINT FK_NOTIFICACAO_VEICULO 
  FOREIGN KEY (TB_VEICULO_ID_VEICULO) 
  REFERENCES RELACAODIRETA.TB_VEICULO(ID_VEICULO);

ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO 
  ADD CONSTRAINT FK_NOTIFICACAO_PATIO 
  FOREIGN KEY (TB_PATIO_ID_PATIO) 
  REFERENCES RELACAODIRETA.TB_PATIO(ID_PATIO);

ALTER TABLE RELACAODIRETA.TB_NOTIFICACAO 
  ADD CONSTRAINT FK_NOTIFICACAO_BOX 
  FOREIGN KEY (TB_BOX_ID_BOX) 
  REFERENCES RELACAODIRETA.TB_BOX(ID_BOX);

-- Criar índices
CREATE INDEX IDX_NOTIF_VEICULO ON RELACAODIRETA.TB_NOTIFICACAO(TB_VEICULO_ID_VEICULO);
CREATE INDEX IDX_NOTIF_PATIO ON RELACAODIRETA.TB_NOTIFICACAO(TB_PATIO_ID_PATIO);
CREATE INDEX IDX_NOTIF_BOX ON RELACAODIRETA.TB_NOTIFICACAO(TB_BOX_ID_BOX);

COMMIT;





